### ISSUE TITLE
🚨querySelector, 쿼리스트링, 템플릿 리터럴과 관련된 의문🚨

### ISSUE THREAD

**Issue by 42KIM** [LM-channel-team-project/wooggooms#87]
메인페이지에 카테고리 리스트를 렌더링하는 함수 코드입니다..
```javascript
function loadCategory() {
  const curMainCat = new URLSearchParams(location.search).get('main');
  const curSubCat = new URLSearchParams(location.search).get('sub');

  if (curMainCat === null || curMainCat === '전체') {
    const all = document.querySelector('.cat-filter-main input[value="전체"]');
    all.classList.add('active-main');
  }
  else {
    const curMainCatBtn = document.querySelector(
      `.cat-filter-main input[value=${curMainCat}]`
    );
    curMainCatBtn.classList.add('active-main');
    const curSubCatBtns = document.querySelectorAll(`.${curMainCatBtn.value}`);
    curSubCatBtns.forEach(Item => {
      Item.classList.add('show-sub');
    });
    if (curSubCat) {
      const curSubCatBtn = document.querySelector(
        `.cat-filter-sub input[value='${curSubCat}']`
      );
      curSubCatBtn.classList.add('active-sub');
    }
  }
}
```
메인페이지에서 카테고리를 변경하면 렌더링이 변하는 함수를 만들고 있는데,
대략적인 상황은 이렇습니다.
```http://localhost:3000/?main=공무원&sub=9급```처럼 주소의 쿼리스트링으로 main과 sub 파라미터가 전달되고 있습니다. 이 파라미터의 값을 ```URLSearchParams```로 가져와 각각의 값에 해당되는 카테고리의 버튼을 ```querySelector```로 선택하고자 하는 상황입니다.

[```좀 더 복잡한 선택자``` 문법](https://developer.mozilla.org/ko/docs/Web/API/Document/querySelector)을 사용하여 ```cat-filter-main``` Div의 자식 중 ```input``` 태그의  ```value```가 위에서 쿼리스트링 파라미터로부터 가져온 값인 ```curMainCat```인 버튼을 선택하고자 합니다.
이를 코드로 나타내면 위에서 10번째 줄에 해당되는,
```javascript
const curMainCatBtn = document.querySelector(
      `.cat-filter-main input[value=${curMainCat}]`
    );
```
입니다.
```cat-filter-sub``` 중분류의 경우도 템플릿 리터럴 내부의 변수만 다를뿐 코드가 정확히 동일합니다.

그런데 기이한 문제가 발생합니다.
대분류의 경우 위와 같이 ```curMainCat```변수를 템플릿 리터럴에 담아 querySelctor문에 적용하면 정상적으로 작동합니다.
그런데 **중분류의 경우** 대분류와 똑같이 코드를 쓰면 querySelector 오류가 발생해서, 제가 위에 코드20번째 줄에 쓴 것 처럼 꼭 템플릿 리터럴을 다시 한 번 따옴표로 감싸야만 작동합니다.
```javascript
 `.cat-filter-sub input[value='${curSubCat}']`
```
여기서 이상함을 느껴 대분류에도 따옴표를 달아보니 마찬가지로 잘 작동합니다.

즉, 대분류의 경우 템플릿리터럴을 따옴표로 감싸든 안 감싸든 작동하는데
중분류는 무조건 감싸야만 작동합니다.

완전히 똑같은 코드인데 도대체 왜 이럴까요? 다른 점이라고는 if문 내부에 있다는 것 뿐인데.................
답답해서 미칠노릇입니다.

**Comment by youngToMaturity** [comment]
이상하네요 if문 내부에 있는것도 사실 `curMainCatBtn`도 else문 내부에 있으니 같은 조건 아닌가요?

**Comment by 42KIM** [comment]
> 이상하네요 if문 내부에 있는것도 사실 `curMainCatBtn`도 else문 내부에 있으니 같은 조건 아닌가요?

정확하게 말하면 curMainCatBtn은 else문 안에,
curSubCatBtn은 else문 안의 if문 안에

있는 상황이긴한데, 그래도 이상하지 않나요???

**Comment by 42KIM** [comment]
@young961027 님의 엄청난 눈썰미로 바로 해결했습니다.
문제는 공무원 대분류 아래의 5급, 7급, 9급 중분류에서 일어나는 것이었는데
쿼리스트링 파라미터에서 가져온 윗 값들의 숫자 부분이 문자열 타입이 아닌 숫자타입으로 인식되어서인 것 같습니다.
